### ISSUE TITLE
Unable to Insert/Update/Update

### ISSUE THREAD

**Issue by ghart14** [supabase-community/postgrest-ex#10]
# Bug report

## Describe the bug

I'm able to perform a Select operation from the table. But anything else is simply returning `{:ok, []}` with no true "successful" write operation to the table. RLS policies were configured as well as fully turned off to try the write. I also used both api keys.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Created a table "users"
2. Disabled RLS just for testing (I may not even need it anyways)
3. Ran this code snippet:
```
Q.from(client, "users")
    |> Q.insert(%{name: "John Smith", age: "40"}, returning: :representation)
    |> Q.execute()
```

## Expected behavior

I expected a return of `{:ok, [some data in here]}` but instead continuously get returned `{:ok, []}`

## System information

- OS: macOS, Debian 11
- Versions: {:supabase_potion, "~> 0.5"},
                  {:supabase_postgrest, "~> 0.1.5"}

**Comment by zoedsoupe** [comment]
solved by #6, It just needs a new release, which I'll be doing by today

**Comment by ghart14** [comment]
Thanks!

**Comment by zoedsoupe** [comment]
release [v0.2.0](https://hexdocs.pm/supabase_postgrest/v0.2.0) launched!
