### ISSUE TITLE
Insert broken

### ISSUE THREAD

**Issue by personsg** [supabase-community/postgrest-ex#2]
Seems insert is broken, the query builder is JASON.encoding the body, and then the Fetcher is JSON encoding a second time, which causes a malformed payload and the insert POST returns a 201 but doesn't actually create a row.

**Comment by zoedsoupe** [comment]
ok, reproduced

**Comment by zoedsoupe** [comment]
actually i didn't get the error itself because of https://github.com/PostgREST/postgrest/issues/1323
